




.build/uno/src/SDC_controller_norf.cpp : src/SDC_controller_norf.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/SDC_controller_norf.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/SDC_controller_norf.cpp
	@true

